name: "Terraform-prod"

on:
  push: 
    branches: ["develop"]
    paths: ["terraform/**"]
  workflow_dispatch:
  
jobs:
  terraform:
    name: "Terraform apply"
    runs-on: "ubuntu-latest"
    steps:
      -  name: "Configure AWS Credentials"
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-region: us-east-1
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

      -  name: checkout 
         uses: actions/checkout@v4
  

      -  name: Terraform init 
         working-directory: ./terraform
         run: terraform init -backend-config='bucket=${{ secrets.AWS_BUCKET_NAME }}' -backend-config='key=${{ secrets.AWS_BUCKET_file }}'

      -  name: Terraform apply
         working-directory: ./terraform      
         run: terraform apply --auto-approve       